In [1]:
# ----- SETUP (RUN ONCE) ------
# Before running make sure you set your fork
# You can find this from your forked repo under the code button
# Only run once, or if you CANNOT cd (change directory)
# into the repository
# For this to work (in colab)
# you must have created a GITHUB token
# and added it to colab.

# Make a change

from google.colab import userdata
email = userdata.get('GITHUB_EMAIL')
username = userdata.get('GITHUB_USERNAME')

# Change this to your forked url!!
gh_repo_url = "https://github.com/nkmwicz/fungal-temp-analysis.git"

# NOTE: set your email as your email
!git config --global user.email {email}

# NOTE: Change your username
!git config --global user.name {username}

# NOTE: change the address to the address of your fork!
!git clone {gh_repo_url}

Cloning into 'fungal-temp-analysis'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 59 (delta 20), reused 4 (delta 4), pack-reused 33 (from 1)
Receiving objects: 100% (59/59), 6.67 MiB | 15.76 MiB/s, done.
Resolving deltas: 100% (29/29), done.

In [2]:
!pip install ncbi-genome-download
!pip install pybarrnap

Collecting ncbi-genome-download
  Downloading ncbi_genome_download-0.3.3-py2.py3-none-any.whl.metadata (10 kB)
Collecting appdirs (from ncbi-genome-download)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: requests>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from ncbi-genome-download) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ncbi-genome-download) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.4.3->ncbi-genome-download) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.4.3->ncbi-genome-download) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.4.3->ncbi-genome-download) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.4.3->ncbi-genome-download) (2026.2.25)
Downloading ncbi_genome_download-0.3.3-py2.py3-none-any.whl (26 kB)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Installing collected packages: appdirs, ncbi-genome-download
Successfully installed appdirs-1.4.4 ncbi-genome-download-0.3.3
Collecting pybarrnap
  Downloading pybarrnap-0.5.1-py3-none-any.whl.metadata (6.8 kB)
Collecting biopython>=1.80 (from pybarrnap)
  Downloading biopython-1.86-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (13 kB)
Collecting pyhmmer>=0.11.0 (from pybarrnap)
  Downloading pyhmmer-0.12.0-cp312-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (14 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython>=1.80->pybarrnap) (2.0.2)
Requirement already satisfied: psutil<8.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from pyhmmer>=0.11.0->pybarrnap) (5.9.5)
Downloading pybarrnap-0.5.1-py3-none-any.whl (11.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 90.2 MB/s eta 0:00:00
Downloading biopython-1.86-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 125.6 MB/s eta 0:00:00
Downloading pyhmmer-0.12.0-cp312-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (4.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 101.8 MB/s eta 0:00:00
Installing collected packages: pyhmmer, biopython, pybarrnap
Successfully installed biopython-1.86 pybarrnap-0.5.1 pyhmmer-0.12.0

In [3]:
# Step 1: Install condacolab
!pip install -q condacolab
import condacolab
condacolab.install()

⏬ Downloading https://github.com/jaimergp/miniforge/releases/download/24.11.2-1_colab/Miniforge3-colab-24.11.2-1_colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:09
🔁 Restarting kernel...

In [1]:
# Step 2: Install tRNAscan-SE from Bioconda
import condacolab
condacolab.check()
!conda install -c bioconda trnascan-se -y

✨🍰✨ Everything looks OK!
Channels:
 - bioconda
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ | / - \ done
Solving environment: / - \ | done

## Package Plan ##

  environment location: /usr/local

  added / updated specs:
    - trnascan-se


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2026.2.25  |       hbd8a1cb_0         144 KB  conda-forge
    certifi-2026.2.25          |     pyhd8ed1ab_0         148 KB  conda-forge
    conda-24.11.3              |  py311h38be061_0         1.1 MB  conda-forge
    infernal-1.1.5             | pl5321h7b50bb2_4         3.7 MB  bioconda
    openssl-3.6.1              |       h35e630c_1         3.0 MB  conda-forge
    perl-5.32.1                | 7_hd590300_perl5        12.7 MB  conda-forge
    trnascan-se-2.0.12         | pl5321h7b50bb2_2         3.1 MB  bioconda
    ------------------------------------------------------------
                                           Total:        24.0 MB

The following NEW packages will be INSTALLED:

  infernal           bioconda/linux-64::infernal-1.1.5-pl5321h7b50bb2_4
  perl               conda-forge/linux-64::perl-5.32.1-7_hd590300_perl5
  trnascan-se        bioconda/linux-64::trnascan-se-2.0.12-pl5321h7b50bb2_2

The following packages will be UPDATED:

  ca-certificates    conda-forge/linux-64::ca-certificates~ --> conda-forge/noarch::ca-certificates-2026.2.25-hbd8a1cb_0
  certifi                           2024.12.14-pyhd8ed1ab_0 --> 2026.2.25-pyhd8ed1ab_0
  conda                             24.11.2-py311h38be061_1 --> 24.11.3-py311h38be061_0
  openssl                                  3.4.0-h7b32b05_1 --> 3.6.1-h35e630c_1



Downloading and Extracting Packages:
perl-5.32.1          | 12.7 MB   | :   0% 0/1 [00:00<?, ?it/s]
infernal-1.1.5       | 3.7 MB    | :   0% 0/1 [00:00<?, ?it/s]

trnascan-se-2.0.12   | 3.1 MB    | :   0% 0/1 [00:00<?, ?it/s]


openssl-3.6.1        | 3.0 MB    | :   0% 0/1 [00:00<?, ?it/s]



conda-24.11.3        | 1.1 MB    | :   0% 0/1 [00:00<?, ?it/s]




certifi-2026.2.25    | 148 KB    | :   0% 0/1 [00:00<?, ?it/s]





perl-5.32.1          | 12.7 MB   | :   8% 0.08226093474124811/1 [00:00<00:01,  1.22s/it]

trnascan-se-2.0.12   | 3.1 MB    | :  80% 0.7963653505063307/1 [00:00<00:00,  7.95it/s]


openssl-3.6.1        | 3.0 MB    | :  65% 0.6523465730209436/1 [00:00<00:00,  6.52it/s]



conda-24.11.3        | 1.1 MB    | :  38% 0.3820240064088151/1 [00:00<00:00,  3.81it/s]



conda-24.11.3        | 1.1 MB    | : 100% 1.0/1 [00:00<00:00,  3.81it/s]

trnascan-se-2.0.12   | 3.1 MB    | : 100% 1.0/1 [00:00<00:00,  7.95it/s]


openssl-3.6.1        | 3.0 MB    | : 100% 1.0/1 [00:00<00:00,  6.52it/s]
infernal-1.1.5       | 3.7 MB    | :   0% 0.004196558995797037/1 [00:00<00:37, 37.89s/it]




certifi-2026.2.25    | 148 KB    | :  11% 0.10818448941860082/1 [00:00<00:01,  1.40s/it]




certifi-2026.2.25    | 148 KB    | : 100% 1.0/1 [00:00<00:00,  1.40s/it]





ca-certificates-2026 | 144 KB    | :  11% 0.11114352194175547/1 [00:00<00:01,  1.50s/it]





perl-5.32.1          | 12.7 MB   | :  41% 0.40516579797928176/1 [00:00<00:00,  2.22it/s]
perl-5.32.1          | 12.7 MB   | :  76% 0.7599928149975013/1 [00:00<00:00,  2.82it/s]
perl-5.32.1          | 12.7 MB   | : 100% 1.0/1 [00:00<00:00,  2.82it/s]



conda-24.11.3        | 1.1 MB    | : 100% 1.0/1 [00:00<00:00,  1.90it/s]



conda-24.11.3        | 1.1 MB    | : 100% 1.0/1 [00:00<00:00,  1.90it/s]


openssl-3.6.1        | 3.0 MB    | : 100% 1.0/1 [00:00<00:00,  6.52it/s]




certifi-2026.2.25    | 148 KB    | : 100% 1.0/1 [00:00<00:00,  1.74it/s]




certifi-2026.2.25    | 148 KB    | : 100% 1.0/1 [00:00<00:00,  1.74it/s]





ca-certificates-2026 | 144 KB    | : 100% 1.0/1 [00:00<00:00,  1.73it/s]





ca-certificates-2026 | 144 KB    | : 100% 1.0/1 [00:00<00:00,  1.73it/s]

trnascan-se-2.0.12   | 3.1 MB    | : 100% 1.0/1 [00:01<00:00,  7.95it/s]






















Preparing transaction: - done
Verifying transaction: | / - \ done
Executing transaction: / - \ | / - \ | / - done

In [3]:
# health check of trnascan
!tRNAscan-SE -h

tRNAscan-SE 2.0.12 (Nov 2022)
Copyright (C) 2022 Patricia Chan and Todd Lowe
                   University of California Santa Cruz
Freely distributed under the GNU General Public License (GPLv3)


Usage: tRNAscan-SE [-options] <FASTA file(s)>

  Scan a sequence file for tRNAs
   -- default: use Infernal & tRNA covariance models
      with eukaryotic sequences
      (use 'Search Mode Options' below to scan other types of sequences)

Search Mode Options:

  -E                          : search for eukaryotic tRNAs (default)
  -B                          : search for bacterial tRNAs
  -A                          : search for archaeal tRNAs
  -M <model>                  : search for mitochondrial tRNAs
                                  options: mammal, vert
  -O                          : search for other organellar tRNAs
  -G                          : use general tRNA model (cytoslic tRNAs from all 3 domains included)
  --mt <model>                : use mito tRNA models for cytosolic/mito detemination
                                  (if not specified, only cytosolic isotype-specific model scan will be performed)
  -I                          : search using Infernal
                                  default use with -E, -B, -A, or -G; optional for -O
      --max                   : maximum sensitivity mode - search using Infernal without hmm filter (very slow)
  -L                          : search using the legacy method (tRNAscan, EufindtRNA, and COVE)
                                  use with -E, -B, -A or -G
  -C  --cove                  : search using COVE analysis only (legacy, extremely slow)
                                  default use with -O
  -H  --breakdown             : show breakdown of primary and secondary structure components to
                                  covariance model bit scores
  -D  --nopseudo              : disable pseudogene checking

Output options:

  -o  --output <file>         : save final results in <file>
  -f  --struct <file>         : save tRNA secondary structures to <file>
  -s  --isospecific <file>    : save results using isotype-specific models in <file>
  -m  --stats <file>          : save statistics summary for run in <file>
                                  (speed, # tRNAs found in each part of search, etc)
  -b  --bed <file>            : save results in BED file format of <file>
  -j  --gff <file>            : save results in GFF3 file format of <file>
  -a  --fasta <file>          : save predicted tRNA sequences in FASTA file format of <file>
  -l  --log <file>            : save log of program progress in <file>
  --detail                    : display prediction outputs in detailed view
  --brief                     : brief output format (no column headers)

  -? #                       : '#' in place of <file> chooses default name for output files
  -p  --prefix <label>        : use <label> prefix for all default output file names

  -d  --progress              : display program progress messages
  -q  --quiet                 : quiet mode (credits & run option selections suppressed)
  -y  --hitsrc                : show origin of hits (Ts=tRNAscan 1.4, Eu=EufindtRNA,
                                  Bo=Both Ts and Eu, Inf=Infernal)

Specify Alternate Cutoffs / Data Files:

  -X  --score <score>         : set cutoff score (in bits) for reporting tRNAs (default=20)
  -g  --gencode <file>        : use alternate genetic codes specified in <file> for
                                  determining tRNA type
  -z  --pad <number>          : use <number> nucleotides padding when passing first-pass
                                  tRNA bounds predictions to CM analysis (default=8)
  --len <length>              : set max length of tRNA intron+variable region for legacy search mode
                                  (default=116bp)
Misc Options:

  -h  --help                  : print this help message
  -c  --conf <file>           : tRNAscan-SE configuration file (default: tRNAscan-SE.conf)
  -Q  --forceow               : do not prompt user before overwriting pre-existing
                                  result files  (for batch processing)

  --match <EXPR>              : search only sequences with names matching <EXPR> string
                                  (<EXPR> may contain * or ? wildcard chars)
  --search <EXPR>             : start search at sequence with name matching <EXPR> string
                                  and continue to end of input sequence file(s)
Special Advanced Options (for testing & special purposes)

  -U                          : search for tRNAs with alternate models defined in configuration file

  -t  --tscan                 : search using tRNAscan only (defaults to strict params)
  --tmode <mode>              : explicitly set tRNAscan params, where <mode>=R or S
                                  (R=relaxed, S=strict tRNAscan v1.3 params)

  -v  --verbose <file>        : save verbose tRNAscan 1.3 output to <file>
  --nomerge                   : Keep redundant tRNAscan 1.3 hits (don't filter out multiple
                                  predictions per tRNA identification)
  -e  --eufind                : search using Eukaryotic tRNA finder (EufindtRNA) only
                                  (defaults to Normal seach parameters when run alone,
                                  or to Relaxed search params when run with Cove)
  --emode <mode>              : explicitly set EufindtRNA params, where <mode>=R, N, or S
                                  (relaxed, normal, or strict)

  --iscore <score>            : manually set "intermediate" cutoff score for EufindtRNA
  -r  --fsres <file>          : save first-pass scan results from EufindtRNA, tRNAscan, or
                                  Infernal hmm in <file> in tabular results format
  --mid                       : fast scan mode - search using Infernal with mid-level strictness of hmm filter
  -F  --falsepos <file>       : save first-pass candidate tRNAs in <file> that were then
                                  found to be false positives by second-pass analysis
  --missed <file>             : save all seqs that do NOT have at least one
                                  tRNA prediction in them (aka "missed" seqs)
  --thread <number>           : number of threads used for running infernal (default is to use available threads)

In [2]:
# ---- Change Directory to repository -----
# Run when first open jupyter notebook.
# If this fails, us above cell.
%cd fungal-temp-analysis

/content/fungal-temp-analysis

In [3]:
%ls

delete_me.csv                     FungiWork.ipynb  README.md
eukaryotes_ncbi_temperatures.csv  LICENSE          temperature_data.tsv

In [4]:
import pandas as pd

df = pd.read_csv("eukaryotes_ncbi_temperatures.csv")
df.head()

,#Organism Name,Organism Groups,Strain,BioSample,BioProject,Assembly,Level,Size(Mb),GC%,Replicons,WGS,Scaffolds,CDS,Release Date,GenBank FTP,RefSeq FTP,Temperature (°C)
0,Neopyropia yezoensis,Eukaryota;Other;Other,NaN,SAMN13316713,PRJNA589917,GCA_009829735.1,Chromosome,107.591,64.8454,chromosome 1:CM020618.1; chromosome 2:CM020619...,WMLA01,28,0,2020-01-03T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/009...,NaN,NaN
1,Emiliania huxleyi CCMP1516,Eukaryota;Protists;Other Protists,CCMP1516,SAMN02744062,PRJNA77753,GCA_000372725.1,Scaffold,167.676,64.5000,NaN,AHAL01,7795,38554,2013-04-19T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000...,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000...,NaN
2,Glycine max,Eukaryota;Plants;Land Plants,NaN,SAMN00002965,PRJNA19861,GCA_000004515.5,Chromosome,978.942,35.1221,chromosome 1:NC_016088.4/CM000834.4; chromosom...,ACUP04,347,74248,2010-01-05T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000...,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000...,NaN
3,Medicago truncatula,Eukaryota;Plants;Land Plants,NaN,SAMN08400029,PRJNA702529,GCA_003473485.2,Chromosome,430.008,33.4462,chromosome 1:NC_053042.1/CM010648.1; chromosom...,PSQE01,42,42683,2018-09-06T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003...,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003...,NaN
4,Solanum lycopersicum,Eukaryota;Plants;Land Plants,NaN,SAMN02981290,PRJNA119,GCA_000188115.3,Chromosome,828.349,35.6991,chromosome 1:NC_015438.3/CM001064.3; chromosom...,AEKE03,3150,37660,2010-12-10T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000...,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000...,NaN

In [5]:
columns = ["#Organism Name", "Organism Groups", "Assembly", "Temperature (°C)"]
df = df[columns]
df.head()

,#Organism Name,Organism Groups,Assembly,Temperature (°C)
0,Neopyropia yezoensis,Eukaryota;Other;Other,GCA_009829735.1,NaN
1,Emiliania huxleyi CCMP1516,Eukaryota;Protists;Other Protists,GCA_000372725.1,NaN
2,Glycine max,Eukaryota;Plants;Land Plants,GCA_000004515.5,NaN
3,Medicago truncatula,Eukaryota;Plants;Land Plants,GCA_003473485.2,NaN
4,Solanum lycopersicum,Eukaryota;Plants;Land Plants,GCA_000188115.3,NaN

In [6]:
df = df.dropna(subset="Temperature (°C)")
df.shape

(972, 4)

In [7]:
df = df.loc[df['Organism Groups'].str.contains("Fung")]
df

,#Organism Name,Organism Groups,Assembly,Temperature (°C)
10,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0
11,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0
12,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0
13,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0
14,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0
...,...,...,...,...
7874,Hanseniaspora lindneri,Eukaryota;Fungi;Ascomycetes,GCA_019649525.1,25.0
7913,Cystobasidium slooffiae,Eukaryota;Fungi;Basidiomycetes,GCA_019775285.1,25.0
7949,[Candida] anglica,Eukaryota;Fungi;Ascomycetes,GCA_019775655.1,25.0
7961,Penicillium brevicompactum,Eukaryota;Fungi;Ascomycetes,GCA_019843585.1,24.0
8157,Agaricus bisporus var. bisporus H97,Eukaryota;Fungi;Basidiomycetes,GCA_000300575.1,24.0

In [8]:
df.drop_duplicates(subset="Assembly")
df

,#Organism Name,Organism Groups,Assembly,Temperature (°C)
10,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0
11,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0
12,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0
13,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0
14,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0
...,...,...,...,...
7874,Hanseniaspora lindneri,Eukaryota;Fungi;Ascomycetes,GCA_019649525.1,25.0
7913,Cystobasidium slooffiae,Eukaryota;Fungi;Basidiomycetes,GCA_019775285.1,25.0
7949,[Candida] anglica,Eukaryota;Fungi;Ascomycetes,GCA_019775655.1,25.0
7961,Penicillium brevicompactum,Eukaryota;Fungi;Ascomycetes,GCA_019843585.1,24.0
8157,Agaricus bisporus var. bisporus H97,Eukaryota;Fungi;Basidiomycetes,GCA_000300575.1,24.0

In [9]:
import re
df['species_root_name'] = df['#Organism Name'].apply(lambda item: " ".join(item.split(" ")[:2]))
df['species_root_name'] = df['species_root_name'].apply(lambda item: re.sub(r"[\[\];'\",\(\).;\-]", "", item))
df

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name
10,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0,Schizosaccharomyces pombe
11,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0,Aspergillus nidulans
12,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0,Aspergillus fumigatus
13,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0,Neurospora crassa
14,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0,Candida albicans
...,...,...,...,...,...
7874,Hanseniaspora lindneri,Eukaryota;Fungi;Ascomycetes,GCA_019649525.1,25.0,Hanseniaspora lindneri
7913,Cystobasidium slooffiae,Eukaryota;Fungi;Basidiomycetes,GCA_019775285.1,25.0,Cystobasidium slooffiae
7949,[Candida] anglica,Eukaryota;Fungi;Ascomycetes,GCA_019775655.1,25.0,Candida anglica
7961,Penicillium brevicompactum,Eukaryota;Fungi;Ascomycetes,GCA_019843585.1,24.0,Penicillium brevicompactum
8157,Agaricus bisporus var. bisporus H97,Eukaryota;Fungi;Basidiomycetes,GCA_000300575.1,24.0,Agaricus bisporus

In [10]:
len(df['species_root_name'].unique())

946

In [11]:
df['duplicate'] = df.duplicated(subset="species_root_name", keep=False)
df

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name,duplicate
10,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0,Schizosaccharomyces pombe,False
11,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0,Aspergillus nidulans,False
12,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0,Aspergillus fumigatus,False
13,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0,Neurospora crassa,False
14,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0,Candida albicans,False
...,...,...,...,...,...,...
7874,Hanseniaspora lindneri,Eukaryota;Fungi;Ascomycetes,GCA_019649525.1,25.0,Hanseniaspora lindneri,False
7913,Cystobasidium slooffiae,Eukaryota;Fungi;Basidiomycetes,GCA_019775285.1,25.0,Cystobasidium slooffiae,False
7949,[Candida] anglica,Eukaryota;Fungi;Ascomycetes,GCA_019775655.1,25.0,Candida anglica,False
7961,Penicillium brevicompactum,Eukaryota;Fungi;Ascomycetes,GCA_019843585.1,24.0,Penicillium brevicompactum,False
8157,Agaricus bisporus var. bisporus H97,Eukaryota;Fungi;Basidiomycetes,GCA_000300575.1,24.0,Agaricus bisporus,False

In [12]:
df = df.loc[~df['#Organism Name'].str.contains(" cf. ")]
df.shape

(954, 6)

In [13]:
df = df.reset_index(drop=True)
df.head()

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name,duplicate
0,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0,Schizosaccharomyces pombe,False
1,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0,Aspergillus nidulans,False
2,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0,Aspergillus fumigatus,False
3,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0,Neurospora crassa,False
4,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0,Candida albicans,False

In [17]:
print('Uninstalling current pyhmmer version...')
!pip uninstall -y pyhmmer

print('Installing pyhmmer version 0.11.0...')
!pip install pyhmmer==0.11.0

Uninstalling current pyhmmer version...
WARNING: Skipping pyhmmer as it is not installed.
Installing pyhmmer version 0.11.0...
Collecting pyhmmer==0.11.0
  Downloading pyhmmer-0.11.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Collecting psutil~=6.0 (from pyhmmer==0.11.0)
  Downloading psutil-6.1.1-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (22 kB)
Downloading pyhmmer-0.11.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 161.2 kB/s eta 0:00:00
Downloading psutil-6.1.1-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (287 kB)
Installing collected packages: psutil, pyhmmer
Successfully installed psutil-6.1.1 pyhmmer-0.11.0

In [ ]:
from numpy import mean, nan
import subprocess, requests, tarfile, os
from zipfile import ZipFile
from pybarrnap import Barrnap
from pybarrnap.utils import load_example_fasta_file

# get fasta files
# unzip fasta
# barrnap fasta file for quality.
# get tRNA & save it in df
# scrape web for it????
is_quality = []
quality_scores = []
quality_mean = []
trna_fasta = []

for row in range(1):
    assembly = df.at[row, 'Assembly']
    url = f"https://api.ncbi.nlm.nih.gov/datasets/v2/genome/accession/{assembly}/download?include_annotation_type=GENOME_FASTA"
    res = requests.get(url)  # this returns a zip folder

    # Define the filename for the downloaded zip file
    zip_filename = f"{assembly}.zip"
    # Save the zip file
    with open(zip_filename, 'wb') as f:
        for chunk in res.iter_content(chunk_size=8192):
            f.write(chunk)
    extract_dir = f"{assembly}_dir"
    if not f"{extract_dir}":
        os.mkdir(extract_dir)

    with ZipFile(zip_filename, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)
    %cd {extract_dir}/ncbi_dataset/data/{assembly}

    fasta_file = os.listdir()[0] # => []
    # Run pybarrnap rRNA prediction
    barrnap = Barrnap(
        fasta_file,
        evalue=1e-6,
        lencutoff=0.8,
        reject=0.25,
        threads=1,
        kingdom="euk",
        accurate=False,
        quiet=False,
    )
    result = barrnap.run()
    # Get rRNA GFF text and print
    # print("\n========== Print rRNA GFF ==========")
    gff_text = result.get_gff_text()
    gff_text1 = [lines for lines in gff_text.split("\n")]
    gff_nums = [
        float(item.split("\t")[5]) for item in gff_text1[1:] if len(item.split('\t'))>6
        ]
    gff_mean = mean(gff_nums)
    print(gff_text)
    print(f"gff_mean: {gff_mean}")

    # Get rRNA features and print
    print("\n========== Print rRNA features ==========")
    genes_set = set()
    needed_genes = {"5S", "5_8S", "18S", "28S"}
    for rec in result.seq_records: # seq_records is a list
        print(rec)
        for feature in rec.features: # features on rec is a list
            qualifiers = feature.qualifiers #feature.id, feature.type, feature.location, feature.qualifiers)
            if "gene" in qualifiers:
                for g in qualifiers["gene"]:
                    genes_set.add(g)

    return_value = None # Quality Metric
    if all([any([needed in g for g in genes_set]) for needed in needed_genes]):
        return_value = True
        quality_nums = gff_nums
        quality_mean = gff_mean
    else:
        return_value = False
        quality_nums = nan
        quality_mean = nan

    output_name = f"{fasta_file}_trna.fasta"
    !tRNAscan-SE --fasta -o ../../../../{output_name} fasta_file

    is_quality.append(return_value)
    quality_scores.append(quality_nums)
    quality_mean.append(quality_mean)
    trna_fasta.append(output_name)
            # qaul_genes = []
            # all three types had to be identified
            # must = '5S', '5_8S', '18S', '28S'

    # Do stuff here with the Fasta file!
    # ✔️ Pybarrnap
    # ✔️Create a quality metric & save to df
    # Save quality metric to df
    # Find tRNA from the fasta
    # Save tRNA to df

    %cd ../../../../
    %ls
    %rm -rf {extract_dir}
    print("\n")
    print(f"{'='*10}")
    print("\n")
    %ls
    # !ncbi-genome-download --section genbank --assembly-accessions {assembly} --formats fasta fungi

/content/fungal-temp-analysis/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2
##gff-version 3
CU329670.1	pybarrnap:0.5.1	rRNA	149660	149774	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	456529	456643	4.7e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	912232	912346	1.9e-21	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	1563477	1563591	2.1e-21	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	2976821	2976935	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	3165398	3165512	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	3547902	3548016	7.9e-20	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	3634373	3634487	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	3830382	3830496	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	3891665	3891779	7.9e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	4184357	4184471	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329670.1	pybarrnap:0.5.1	rRNA	4240852	4240966	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	464529	464643	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	520305	520419	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	569153	569267	1.0e-20	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	783261	783375	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	1199929	1200043	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	1406587	1406701	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	1504375	1504489	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	2032412	2032526	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	2261373	2261487	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	2322735	2322849	2.8e-21	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	2442703	2442817	1.0e-20	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	3096971	3097072	1.2e-07	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	3171574	3171678	3.1e-12	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	3938580	3938694	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	4161625	4161735	1.0e-20	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329671.1	pybarrnap:0.5.1	rRNA	4210383	4210497	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	16	1389	0	-	.	Name=18S_rRNA;product=18S ribosomal RNA (partial);Dbxref=RFAM:RF01960;Note=aligned only 73.52 percent of the 18S ribosomal RNA
CU329672.1	pybarrnap:0.5.1	rRNA	6045	9537	0	-	.	Name=28S_rRNA;product=28S ribosomal RNA;Dbxref=RFAM:RF02543
CU329672.1	pybarrnap:0.5.1	rRNA	9845	9997	6.7e-45	-	.	Name=5_8S_rRNA;product=5.8S ribosomal RNA;Dbxref=RFAM:RF00002
CU329672.1	pybarrnap:0.5.1	rRNA	10420	12259	0	-	.	Name=18S_rRNA;product=18S ribosomal RNA;Dbxref=RFAM:RF01960
CU329672.1	pybarrnap:0.5.1	rRNA	16915	20407	0	-	.	Name=28S_rRNA;product=28S ribosomal RNA;Dbxref=RFAM:RF02543
CU329672.1	pybarrnap:0.5.1	rRNA	20715	20867	6.7e-45	-	.	Name=5_8S_rRNA;product=5.8S ribosomal RNA;Dbxref=RFAM:RF00002
CU329672.1	pybarrnap:0.5.1	rRNA	21290	23129	0	-	.	Name=18S_rRNA;product=18S ribosomal RNA;Dbxref=RFAM:RF01960
CU329672.1	pybarrnap:0.5.1	rRNA	523319	523433	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	853316	853430	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	926144	926258	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	1370036	1370150	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	1474261	1474375	4.4e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	1690947	1691061	4.4e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	1702126	1702240	7.8e-22	+	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	2308168	2308282	7.8e-22	-	.	Name=5S_rRNA;product=5S ribosomal RNA;Dbxref=RFAM:RF00001
CU329672.1	pybarrnap:0.5.1	rRNA	2440995	2442834	0	+	.	Name=18S_rRNA;product=18S ribosomal RNA;Dbxref=RFAM:RF01960
CU329672.1	pybarrnap:0.5.1	rRNA	2443257	2443409	6.7e-45	+	.	Name=5_8S_rRNA;product=5.8S ribosomal RNA;Dbxref=RFAM:RF00002
CU329672.1	pybarrnap:0.5.1	rRNA	2443717	2447209	0	+	.	Name=28S_rRNA;product=28S ribosomal RNA;Dbxref=RFAM:RF02543
CU329672.1	pybarrnap:0.5.1	rRNA	2451884	2452883	1.3e-272	+	.	Name=18S_rRNA;product=18S ribosomal RNA (partial);Dbxref=RFAM:RF01960;Note=aligned only 53.50 percent of the 18S ribosomal RNA

gff_mean: 2.553257446811402e-09

========== Print rRNA features ==========
ID: CU329670.1
Name: CU329670.1
Description: CU329670.1 Schizosaccharomyces pombe strain 972h- genome assembly, chromosome: I
Number of features: 12
Seq('GATCACGTACATCACCTTGTAAGAATTTATCTGCAATAGTCCTTCGGTATTGTA...ATC')
ID: CU329671.1
Name: CU329671.1
Description: CU329671.1 Schizosaccharomyces pombe strain 972h- genome assembly, chromosome: II
Number of features: 16
Seq('GATCTCGCAACTCTTAATAAAGCTAATTCCTGCTAATTCGCTATACACTAAATC...TTT')
ID: CU329672.1
Name: CU329672.1
Description: CU329672.1 Schizosaccharomyces pombe strain 972h- genome assembly, chromosome: III
Number of features: 19
Seq('GATCAGCCAAAATGGCTGATCCAGCTATTTAGCAGGTTAAGGTCTCGTTCGTTA...GGG')
ID: X54421.1
Name: X54421.1
Description: X54421.1 Schizosaccharomyces pombe complete mitochondrial genome
Number of features: 0
Seq('AATGTGTAATTTGAATCAATTTCTATCCTTTTAAAAATACATCATAAAGTGTAC...TGT')
/content/fungal-temp-analysis/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2
GCA_000002945.2_ASM294v2_genomic.fna  GCA_000002945.2_dir/  GCA_000002945.2.zip

In [ ]:
for file in os.listdir():
    if file.endswith(".fna"):
        bites = os.path.getsize(file)
        mbs = bites / 1000000
        with open(file, "r") as f:
            basepairs = f.read()
            len_bp = len(basepairs)
            basepair_mb = len_bp / 1000000
        print(f"{file}: {mbs} MB")
        print(f"{file}: {basepair_mb} MB")

GCA_000002945.2_ASM294v2_genomic.fna: 12.748959 MB
GCA_000002945.2_ASM294v2_genomic.fna: 12.748959 MB

In [ ]:
%%bash
# Loop over all files in the current directory
for file in *;
do
  # Check if it's a regular file (not a directory)
  if [ -f "$file" ]; then
    echo "Processing file: $file"
    # You can add your commands here to process each file
    # For example, to print the first line of each file:
    # head -n 1 "$file"
  fi
done

### Explanation:

*   `%%bash`: This is a Jupyter/Colab magic command that allows you to run the cell content as a bash script.
*   `for file in *; do ... done`: This is the basic structure of a `for` loop in bash. The `*` is a wildcard that expands to all files and directories in the current directory.
*   `if [ -f "$file" ]; then ... fi`: This condition checks if `$file` refers to a regular file (not a directory or other special file type). The double quotes around `$file` are crucial to handle filenames that contain spaces or special characters correctly.
*   `echo "Processing file: $file"`: This line prints the name of the file being processed.

If you specifically want to loop over files with a certain extension, like `.txt`, you can change `*` to `*.txt`:

```bash
%%bash
for file in *.txt;
do
  if [ -f "$file" ]; then
    echo "Processing text file: $file"
  fi
done
```

**Important Note**: Avoid parsing the output of `ls` directly in scripts (e.g., `for file in $(ls); do ...`). This is considered bad practice because `ls` output is formatted for human readability, not for programmatic parsing, and can cause issues with filenames containing spaces, newlines, or other special characters.

In [ ]:
%ls

GCA_000002945.2_ASM294v2_genomic.fna  GCA_000002945.2.zip

In [ ]:
%ls

delete_me.csv                     FungiWork.ipynb       GCA_000002945.2.zip  README.md
eukaryotes_ncbi_temperatures.csv  GCA_000002945.2_dir/  LICENSE              temperature_data.tsv

In [ ]:
%cd data/
%ls

/content/fungal-temp-analysis/GCA_000002945.2_dir/GCA_000002945.2_dir/ncbi_dataset/data
assembly_data_report.jsonl  dataset_catalog.json  GCA_000002945.2/

In [ ]:
%cd {assembly}
%ls

/content/fungal-temp-analysis/GCA_000002945.2_dir/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2
GCA_000002945.2_ASM294v2_genomic.fna

In [ ]:
%rm -rf {extract_dir}

In [ ]:
duplicated_species = df.loc[df['duplicate'] == True]
duplicated_species

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name,duplicate
47,Cryptococcus neoformans var. neoformans JEC21,Eukaryota;Fungi;Basidiomycetes,GCA_000091045.1,27.0,Cryptococcus neoformans,True
1069,Saccharomyces cerevisiae x Saccharomyces kudri...,Eukaryota;Fungi;Ascomycetes,GCA_009665985.1,25.0,Saccharomyces cerevisiae,True
1495,Ogataea polymorpha,Eukaryota;Fungi;Ascomycetes,GCA_001664045.1,25.0,Ogataea polymorpha,True
1541,Saccharomyces cerevisiae x Saccharomyces uvarum,Eukaryota;Fungi;Ascomycetes,GCA_013180185.1,25.0,Saccharomyces cerevisiae,True
2300,Magnusiomyces capitatus NRRL Y-17686,Eukaryota;Fungi;Ascomycetes,GCA_900497725.1,25.0,Magnusiomyces capitatus,True
3227,Saccharomycopsis fibuligera,Eukaryota;Fungi;Ascomycetes,GCA_001936155.1,25.0,Saccharomycopsis fibuligera,True
4451,Magnusiomyces capitatus CNRMA 12.647,Eukaryota;Fungi;Ascomycetes,GCA_000817185.1,25.0,Magnusiomyces capitatus,True
4962,Cryptococcus neoformans AD hybrid,Eukaryota;Fungi;Basidiomycetes,GCA_006992865.1,27.0,Cryptococcus neoformans,True
5187,Saccharomyces cerevisiae x Saccharomyces eubay...,Eukaryota;Fungi;Ascomycetes,GCA_009665555.1,25.0,Saccharomyces cerevisiae,True
5188,Saccharomyces cerevisiae x Saccharomyces eubay...,Eukaryota;Fungi;Ascomycetes,GCA_009666275.1,25.0,Saccharomyces cerevisiae,True
5189,Saccharomyces cerevisiae x Saccharomyces eubay...,Eukaryota;Fungi;Ascomycetes,GCA_009667055.1,25.0,Saccharomyces cerevisiae,True
5190,Saccharomyces cerevisiae x Saccharomyces kudri...,Eukaryota;Fungi;Ascomycetes,GCA_009666465.1,25.0,Saccharomyces cerevisiae,True
5661,Saccharomyces cerevisiae x Saccharomyces kudri...,Eukaryota;Fungi;Ascomycetes,GCA_013180725.1,25.0,Saccharomyces cerevisiae,True
7812,Ogataea polymorpha x Ogataea parapolymorpha,Eukaryota;Fungi;Ascomycetes,GCA_019381815.1,25.0,Ogataea polymorpha,True

In [ ]:
!pip install ncbi-genome-download

Collecting ncbi-genome-download
  Downloading ncbi_genome_download-0.3.3-py2.py3-none-any.whl.metadata (10 kB)
Collecting appdirs (from ncbi-genome-download)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: requests>=2.4.3 in /usr/local/lib/python3.11/dist-packages (from ncbi-genome-download) (2.32.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from ncbi-genome-download) (4.67.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.4.3->ncbi-genome-download) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.4.3->ncbi-genome-download) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.4.3->ncbi-genome-download) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.4.3->ncbi-genome-download) (2025.1.31)
Downloading ncbi_genome_download-0.3.3-py2.py3-none-any.whl (26 kB)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Installing collected packages: appdirs, ncbi-genome-download
Successfully installed appdirs-1.4.4 ncbi-genome-download-0.3.3

In [ ]:
df["short_name"] = df["#Organism Name"].str.split(" ")[0]
df

KeyError: 0

In [ ]:
# make sure to run this cell to have access to this function below
def commit_and_push(repo_url, message):
    import os
    import subprocess
    from google.colab import userdata

    try:
        # change your username from mine to yours.
        username = userdata.get("GITHUB_USERNAME")
        token = userdata.get("GITHUB_TOKEN")
        !git add .
        !git commit -m {message}
        !git push https://{username}:{token}@github.com/{username}/fungal-temp-analysis.git
        print("Changes Saved to GitHub!")
    except Exception as e:
        print(e)

# Only call this function if you want to
def catch_up_to_main_repo():
    import os
    from google.colab import userdata
    try:
        username = userdata.get("GITHUB_USERNAME")
        token = userdata.get("GITHUB_TOKEN")
        main_repo = "https://github.com/nkmwicz/fungal-temp-analysis.git"
        !git remote add upstream {main_repo}
        !git fetch upstream
        !git merge upstream/main
        !git push https://{username}:{token}@github.com/{username}/fungal-temp-analysis.git
    except Exception as e:
        print(e)

In [ ]:
# SOME NOTES
# %ls shows the available files in the repo to get names of files
# to read a tsv, use pd.read_csv but pass in sep="\t"
# to reperesent tabs as separators
%ls

delete_me.csv                     FungiWork.ipynb  README.md
eukaryotes_ncbi_temperatures.csv  LICENSE          temperature_data.tsv

In [ ]:
# columns needed
# remove rows that aren't fungi ()
# remove those without temp.
# name, assembly, temp

In [ ]:
import pandas as pd
df = pd.read_csv("./delete_me.csv")
df.loc[len(df)] = [11,12,13,14]
df.to_csv("./delete_me.csv", index=False)

In [ ]:
# ----Keep as last cell----
# Use to save changes in repo that are not in this file.
# To save this file, use ctrl + s
# Then set commit message location, branch, etc.

# Change repo url to your forked url
url = "https://github.com/nkmwicz/fungal-temp-analysis.git"
# Change commit message
commit_and_push(url, "made changes to csv")

On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 313 bytes | 313.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/nkmwicz/fungal-temp-analysis.git
   c74cf0e..cf49267  main -> main
Changes Saved to GitHub!